### ISSUE TITLE
Undocumented reference in <collection>/roles/install/tasks/repositories.yml

### ISSUE THREAD

**Issue by ghost** [xlab-steampunk/steampunk.unit#2]
Hi everyone, the tech writer for NGINX Unit here. Couldn't find the docs repo, so I'm dropping a note here instead.
 
First, thanks for promoting our project, much appreciated!

Second, I'm considering adding a brief section on your NGINX Unit Ansible collection to the official docs (somewhere here: https://unit.nginx.org/installation/#community-repositories), but I've ran into the following issue during a replay:
```
TASK [install : Prepare package repositories] *******************************************************************************************************************
included: /home/vagrant/.ansible/collections/ansible_collections/steampunk/unit/roles/install/tasks/repositories.yml for 127.0.0.1

TASK [install : Prepare package repositories] *******************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"reason": "Could not find or access '/home/vagrant/ansible/Ubuntu/repositories.yml' on the Ansible Controller."}
```
Obviously, the collection's `<collection>/roles/install/tasks/repositories.yml` refers to the missing file.
The quickstart was unfortunately missing any mentions of `repositories.yml`, so I jury-rigged the following:
```
vagrant@ubuntu-focal:~/ansible$ cat Ubuntu/repositories.yml
---
- name: Add nginx signing key (Debian/Ubuntu)
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present
  when: ansible_os_family == "Debian"

- name: Add Unit repository (Ubuntu 20.04)
  apt_repository: repo={{item}} state=present update_cache=yes
  with_items:
    - 'deb https://packages.nginx.org/unit/ubuntu/ focal unit'
    - 'deb-src https://packages.nginx.org/unit/ubuntu/ focal unit'
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "20")
```

After this, everything went smoothly.

My question is, where does this file (repositories.yml) come from in your reference setup? Am I right in assuming it's omitted in the quickstart by accident only? Maybe I should provide the instructions on its creation in our docs to smoothen the process for the reader?

Admittedly, I'm new to Ansible, so I may be chasing windmills here.

P.S. There's a small typo as well: https://docs.steampunk.si/unit/quickstart.html
`name:steampunk.unit.install` - missing space.
